# ──────────────────────────────────────────────────────────────────────────
# Site basics (yours may already have most of this)
title:   "Hector Chaires"            # your site’s title
baseurl: ""                          # no sub‐folder
url:     "https://quantaquaestio.github.io"

# ── Theme & Plugins ───────────────────────────────────────────────────────
remote_theme: mmistakes/minimal-mistakes@4.27.1
plugins:
  - jekyll-include-cache

# ── Force Dark Palette ────────────────────────────────────────────────────
minimal_mistakes_skin: "dark"        # ← switches to the inverted (dark) scheme

# ── Optional Extras ───────────────────────────────────────────────────────
paginate: 5                          # show n posts per page on the home layout
search: true                         # enable the search box in the header

author:
  avatar: "/assets/images/avatar.jpg"
  name:   "Hector Chaires"
  bio:    "Computational Chemist • ML"
  location: "Cambridge, MA"
  email:  "you@example.com"
  googlescholar: "https://scholar.google.com/…"
  github: "hectorchaires"
  bluesky: "hector.bsky.social"
  linkedin: "https://linkedin.com/in/yourprofile"
  twitter:  "hectorchaires"
